server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/chatdb?useSSL=false&serverTimezone=UTC
    username: root
    password: password123
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
